// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://svdtiudkmtgxzduimtrz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InN2ZHRpdWRrbXRneHpkdWltdHJ6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM5OTQ1MTMsImV4cCI6MjA1OTU3MDUxM30.5LLWdxduu9wJ9XC9k1WemlRbwfpchKSGlqNdlRt69pY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);